version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_DSN=basegouser:basegopassword@tcp(db:3306)/basegov1?charset=utf8mb4&parseTime=True&loc=Local
    volumes:
      - ./docs:/app/docs

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: basegov1
      MYSQL_USER: basegouser
      MYSQL_PASSWORD: basegopassword
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql_data: